project:
  type: website
  
render:
    - "*.qmd"
    - "!rum_2.qmd"

website:
  title: "Unequal Recreational Losses?"
  search: true
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mdcev.qmd
        text: MDCEV
      - href: rum.qmd
        text: Random Utility

    tools:
      - icon: youtube
        href: https://www.youtube.com/@Prof.Iguana
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/loweas/rec_res
          - text: Report a Bug
            href:  https://github.com/loweas/rec_res/issues

# Add this section below:
execute:
  message: false
  warning: false
  
format:
  html:
    theme: cosmo
    toc: true